services:
  db:
    image: postgres:16.6
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: personal_financial_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
